name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  scout-import-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [16.x]
        typesense-version: [0.24.0]

#    container:
#      image: kirschbaumdevelopment/laravel-test-runner:8.1

#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_DATABASE: test
#          MYSQL_USER: default
#          MYSQL_PASSWORD: root
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 33306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#    services:
#      mysql:
#        image: mysql:5.7
#        env:
#          MYSQL_DATABASE: test
#          MYSQL_USER: default
#          MYSQL_PASSWORD: root
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: ${{ matrix.typesense-version }}
          typesense-port: 8108
          typesense-api-key: xyz

      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health

#      - name: Create MySQL Database
#        run: |
#          sudo apt-get update && sudo apt-get install -y mysql-client
#          sudo chmod 777 /etc/mysql/conf.d/mysql.cnf
#          echo "bind-address           = 0.0.0.0" >> /etc/mysql/conf.d/mysql.cnf
#          sudo service mysql restart
#          sudo mysql -e 'CREATE SCHEMA `test` CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON `test`.* TO default@localhost IDENTIFIED BY "root"; FLUSH PRIVILEGES;'


      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          container port: 3306 # Optional, default value is 3306. The port of container
          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'root' # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'default' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'root' # Required if "mysql user" exists. The password for the "mysql user"

      - name: Create MySQL User
        run: |
          mysql -e "CREATE DATABASE 'test';"

      - name: Grant Permissions to MySQL User
        run: |
          mysql -e "GRANT ALL PRIVILEGES ON test.* TO 'default'@'localhost';"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: arayiksmbatyan/scout-import-tests

      - name: Composer Validate
        run: composer validate

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress

      - name: Prepare Application Environment
        run: |
          cp .env.example .env

      - name: Run Migrations and Seeders
        run: php artisan migrate --seed

      - name: Run Tests
        run: php artisan test
