name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  scout-import-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [16.x]
        typesense-version: [0.24.0]

#    container:
#      image: kirschbaumdevelopment/laravel-test-runner:8.1

#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_DATABASE: test
#          MYSQL_USER: default
#          MYSQL_PASSWORD: root
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 33306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Start Typesense
        uses: jirevwe/typesense-github-action@v1.0.1
        with:
          typesense-version: ${{ matrix.typesense-version }}
          typesense-port: 8108
          typesense-api-key: xyz

      - name: Curl Typesense
        run: sleep 10 && curl http://localhost:8108/health
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          submodules: 'recursive'
      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install mysql-server
      - name: Start MySQL Server
        run: sudo service mysql start

      - name: Create MySQL Database
        run: |
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '';"
          sudo mysql -e "CREATE USER 'default'@'localhost' IDENTIFIED BY 'root';"
          sudo mysql -e "CREATE DATABASE test;"
          sudo mysql -e "GRANT ALL ON test.* TO 'default'@'localhost' IDENTIFIED BY 'root';"


      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: arayiksmbatyan/scout-import-tests

      - name: Composer Validate
        run: composer validate

      - name: Cache Composer Packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: |
           composer update --prefer-dist --no-interaction --no-progress

      - name: Prepare Application Environment
        run: |
          cp .env.example .env

      - name: Run Migrations and Seeders
        run: php artisan migrate --seed

      - name: Run Tests
        run: php artisan test
